### ISSUE TITLE
Two issues - Light Pillars / Gold

### ISSUE THREAD

**Issue by updawg** [Caedendi/D2RMM-Loot-Filter-Extended#6] opened 2023-10-19 16:40 UTC
I tested this on a fresh install of D2R with this as the only mod added in D2RMM. I can't for the life of me get pillars to only appear on Jewels and not Gems. It's either both or none. I've tried setting jewels to disabled and ensured that the option for light pillars not to appear on disabled items is enabled.

Secondly, I see unexpected behavior with Gold G vs White G. Gold G shows the correct gold colored G after the amount. White G shows the entire word of Gold.

Thanks for this awesome project! It really adds much needed quality of life to the game.

**Comment by Caedendi** [comment] 2023-10-19 22:11
> I tested this on a fresh install of D2R with this as the only mod added in D2RMM. I can't for the life of me get pillars to only appear on Jewels and not Gems. It's either both or none. I've tried setting jewels to disabled and ensured that the option for light pillars not to appear on disabled items is enabled.

That's the intended behaviour. Jewels share the same textures as gems so its all or nothing. Afraid I can't do much about it as I dont want to add new separate textures for jewels just to make this work. I mentioned this in the description If you hover over the question mark next to the Gems & Jewels option in the light pillars section. Same for Khalim's organs for the Act 3 questline and the Pandemonium organs for the ubers. Gems and Jewels are very useful anyways, pick em up;)

> Secondly, I see unexpected behavior with Gold G vs White G. Gold G shows the correct gold colored G after the amount. White G shows the entire word of Gold.

I'll have to look into this, thanks for mentioning it. I'll leave this issue open until v3.0.0 is released since that update is another major code rewrite. I won't be patching v2 in the meantime.

> Thanks for this awesome project! It really adds much needed quality of life to the game.

Thanks! Appreciate it. If you have any suggestions or opinions I'll be happy to hear them.

**Comment by updawg** [comment] 2023-10-20 00:06
I think the confusion for me came from the light pillar section. There is an option listed to turn off light pillars for disabled items. I appreciate the clarification. I guess I'll leave light pillars off for those items because gems drop far too often to lump together with jewels, which I think leads to notification fatigue.

**Comment by Caedendi** [comment] 2024-06-16 22:54
Totally forgot about this issue since I never properly finished v3.0.0.
AFAIK it just works now, could use some extra testing to be sure once I finish v4.0.0. I'ma close this for now since it's so old.

**Closed as completed by Caedendi** 2024-06-16 22:54 UTC
